virustotal_api_key: ""
yara_rules_dir: "./rules/yara"
floss_binary: "./bin/floss"
capa_binary: "./bin/capa"
output_dir: "./reports"
log_level: "INFO"
module_timeout_seconds: 60
enabled_modules:
  - file_intake
  - pe_analysis
  - string_analysis
  - ioc_extractor
  - capa_analysis
  - yara_scanner
  - doc_analysis
  - pdf_analysis
  - virustotal
dynamic_provider: "none"   # none | speakeasy | vm_worker | cape
